#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Rendezvous-Publish
version:      0.01
version_from: lib/POE/Component/Rendezvous/Publish.pm
installdirs:  site
requires:
    POE:                           0.3009
    Net::Rendezvous::Publish:      0.03
    Test::More:                    0.54

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
